baseURL = 'https://oungin04-math.github.io/'
languageCode = 'ko-kr'
title = 'Algebra'
theme = 'PaperMod'

[params]
  defaultTheme = "auto"
  # 수학 수식(LaTeX) 활성화 설정
  math = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "Categories"    # 화면에 보일 이름 (예: 분류, 목차)
    url = "/categories/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 20